/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.6.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as addSubmission from "../addSubmission.js";
import type * as competition from "../competition.js";
import type * as getUserInfo from "../getUserInfo.js";
import type * as listParticipants from "../listParticipants.js";
import type * as listSubmissions from "../listSubmissions.js";
import type * as storeUser from "../storeUser.js";
import type * as updateThumbnail from "../updateThumbnail.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  addSubmission: typeof addSubmission;
  competition: typeof competition;
  getUserInfo: typeof getUserInfo;
  listParticipants: typeof listParticipants;
  listSubmissions: typeof listSubmissions;
  storeUser: typeof storeUser;
  updateThumbnail: typeof updateThumbnail;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
